version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app/src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: book_ninja

volumes:
  mongo_data:
